### ISSUE TITLE
aws-sdk package is included when packaging and sending to aws lambda

### ISSUE THREAD

**Issue by zeuzere** [rafaelrpinto/dynamodb-store#1]
I was wondering, if it was possible to put the aws-sdk package in the optionalDependencies...

  "optionalDependencies": {
    "aws-sdk": "^2.100.0",
  },

instead of the 

  "dependencies": {
    "aws-sdk": "^2.100.0",
    "express-session": "^1.15.5"
  },

When i deploy with Claudia i use  
   _claudia update **--no-optional-dependencies**...._
to avoid sending 30Mo+ in lambda ( and a best practice also recommended by AWS)

But, i don't know, in sub-package, if the  --no-optional-dependencies will be apply...
Example: 
       If i dont use dynamodb-store, its like 5-6-mo in lambda and when i use it, its like 10Mo+ just because it incluse aws-sdk...

Those that dont use --no-optional-dependencies will not be affected by that and those that want it will benefit of this... ( If this feature can be apply on sub-package)

Thanks!
Ps.: I love this tool it work great... ( Api Gateway + lambda + DynamoDB )
Yves Laroche

**Comment by rafaelrpinto** [comment]
@zeuzere 

Glad to know this project helped you :)

I pushed v1.0.8 and tested a claudia deployment with `--no-optional-dependencies`. It works as you described.

Thanks for the feedback and let me know if you find any other issues or have more suggestions.

Cheers,
