### ISSUE TITLE
Table already exists

### ISSUE THREAD

**Issue by TiagoXavi** [rafaelrpinto/dynamodb-store#11]
How to skip DynamoDB Table creation if already exists?

It return a error when try to create a table that already exist. What is the proper way to use this tool? Put a hash sufix in the name to avoid conflicts every deploy?

**Comment by rafaelrpinto** [comment]
@TiagoXavi,
Could you share a code snippet on how you are creating the store and also paste here the stack trace?
Thanks,

**Comment by TiagoXavi** [comment]
Thanks for the reply
![image](https://user-images.githubusercontent.com/22452335/181995573-647440b0-5082-4b49-bcb6-c0f5d9314f33.png)
![image](https://user-images.githubusercontent.com/22452335/181995589-e3fe5ef5-552c-456d-b71f-496b3158d635.png)

**Comment by rafaelrpinto** [comment]
The flow that checks if the table exists was poorly made by me at the time. 

Probably the key you are using do not have permission to describe the table, so the call fails and the code thinks the table does not exists. Then it tries to create the table again, which causes the resource in use error.

Could you make sure the key you are using has the `dynamodb:DescribeTable` permission and try again, please?

**Comment by TiagoXavi** [comment]
@rafaelrpinto yes, that permission was the problem. Just worked. Thanks!

**Comment by rafaelrpinto** [comment]
:+1:
